# Generated by Django 4.1.5 on 2023-01-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новость', max_length=200, verbose_name='название')),
                ('anons', models.CharField(default='Новость', max_length=200, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
